require('core.plugins_config.lsp-zero')
require('core.plugins_config.treesitter')
require('core.plugins_config.colorsheme')
require('core.plugins_config.telescope')
require('core.plugins_config.nvim-tree')
require('core.plugins_config.which-key')
